// Generated by CoffeeScript 1.3.3
(function() {

  exports.extend = function(client) {
    client.prototype.getMediaFile = function(id, company, hash, cb) {
      var query;
      query = {
        id: id,
        c: company,
        h: hash
      };
      return this.get('/core/media/media.nl', {
        query: query
      }, cb);
    };
    client.prototype.downloadMediaFile = function(id, company, hash, cb) {
      var query;
      query = {
        id: id,
        c: company,
        h: hash,
        _xd: 'T'
      };
      return this.get('/core/media/media.nl', {
        query: query
      }, cb);
    };
    client.prototype.downloadMediaFolder = function(id, cb) {
      var query;
      query = {
        id: id,
        _xd: 'T',
        e: 'T'
      };
      return this.get('/core/media/downloadfolder.nl', {
        query: query
      }, cb);
    };
    client.prototype.getSiteMedia = function(id, cb) {
      return this.get('/app/site/media/sitemedia.nl', {
        query: {
          id: id
        }
      }, cb);
    };
    return client.prototype.previewMediaFile = function(id, cb) {
      return this.get('/core/media/previewmedia.nl', {
        query: {
          id: id
        }
      }, cb);
    };
  };

}).call(this);
