// Generated by CoffeeScript 1.3.3
(function() {
  var ItemShipRequest, RatesRequest, ShipItem, ShipPackage, ShipTaxItemRequest, xml,
    __slice = [].slice,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  xml = require('../xml');

  ItemShipRequest = function(shipMethod) {
    return {
      ItemShipRequest: {
        ShipMethod: shipMethod
      }
    };
  };

  ShipTaxItemRequest = function(entityId, state, zip, country) {
    return {
      ShipTaxItemRequest: {
        Entity: entityId,
        State: state,
        Zip: zip,
        Country: country
      }
    };
  };

  RatesRequest = (function() {

    function RatesRequest(params, packages, items) {
      if (params == null) {
        params = {};
      }
      this.packages = packages != null ? packages : [];
      this.items = items != null ? items : [];
      this.requestSrc = params.requestSrc;
      this.ratesCarrier = params.ratesCarrier;
      this.entityId = params.entityId;
      this.bIsItemLineRates = params.bIsItemLineRates;
      this.destCity = params.destCity;
      this.destState = params.destState;
      this.destZip = params.destZip;
      this.destCountry = params.destCountry;
      this.shipMethod = params.shipMethod;
      this.salesOrderId = params.salesOrderId;
      this.isResidential = params.isResidential;
      this.isThirdPartyAcct = params.isThirdPartyAcct;
      this.thirdPartyCarrier = params.thirdPartyCarrier;
      this.isPackagesReload = params.isPackagesReload;
      this.isDefaultRequest = params.isDefaultRequest;
      this.currency = params.currency;
      this.tranFxRate = params.tranFxRate;
      this.subsidiary = params.subsidiary;
      this.testId = params.testId;
      this.overrideShippingCost = params.overrideShippingCost;
      this.isDynamicScriptingRequest = params.isDynamicScriptingRequest;
      if (params.packages != null) {
        addPackages(params.packages);
      }
      if (params.items != null) {
        addItems(params.items);
      }
    }

    RatesRequest.prototype.addPackages = function() {
      var p, packages, _i, _len, _results;
      packages = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      _results = [];
      for (_i = 0, _len = packages.length; _i < _len; _i++) {
        p = packages[_i];
        if (typeof pis('object')) {
          if (p.toXML != null) {
            _results.push(this.packages.push(p));
          } else {
            _results.push(this.packages.push(new ShipPackage(p)));
          }
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    };

    RatesRequest.prototype.removePackages = function() {
      var leftover, numbers, p;
      numbers = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      leftover = (function() {
        var _i, _len, _ref, _ref1, _results;
        _ref = this.packages;
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          p = _ref[_i];
          if (_ref1 = p.number, __indexOf.call(numbers, _ref1) < 0) {
            _results.push(p);
          }
        }
        return _results;
      }).call(this);
      return this.packages = leftover != null ? leftover : [];
    };

    RatesRequest.prototype.addItems = function() {
      var i, items, _i, _len, _results;
      items = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      _results = [];
      for (_i = 0, _len = items.length; _i < _len; _i++) {
        i = items[_i];
        if (typeof i === 'object') {
          if (i.toXML != null) {
            _results.push(this.items.push(i));
          } else {
            _results.push(this.items.push(new ShipItem(i)));
          }
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    };

    RatesRequest.prototype.removeItems = function() {
      var i, keys, leftover;
      keys = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      leftover = (function() {
        var _i, _len, _ref, _ref1, _results;
        _ref = this.items;
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          i = _ref[_i];
          if (_ref1 = i.key, __indexOf.call(keys, _ref1) < 0) {
            _results.push(i);
          }
        }
        return _results;
      }).call(this);
      return this.items = leftover != null ? leftover : [];
    };

    RatesRequest.prototype.toXML = function() {
      var item, pkg, _ref, _ref1, _ref10, _ref11, _ref12, _ref13, _ref14, _ref15, _ref16, _ref17, _ref18, _ref19, _ref2, _ref20, _ref3, _ref4, _ref5, _ref6, _ref7, _ref8, _ref9;
      return {
        RatesRequest: {
          RequestSrc: (_ref = this.requestSrc) != null ? _ref : null,
          RatesCarrier: (_ref1 = this.ratesCarrier) != null ? _ref1 : null,
          EntityId: (_ref2 = this.entityId) != null ? _ref2 : null,
          IsItemLineRates: (_ref3 = this.bIsItemLineRates) != null ? _ref3 : null,
          DestCity: (_ref4 = this.destCity) != null ? _ref4 : null,
          DestState: (_ref5 = this.destState) != null ? _ref5 : null,
          DestZip: (_ref6 = this.destZip) != null ? _ref6 : null,
          DestCountry: (_ref7 = this.destCountry) != null ? _ref7 : null,
          ShipMethod: (_ref8 = this.shipMethod) != null ? _ref8 : null,
          SalesOrderId: (_ref9 = this.salesOrderId) != null ? _ref9 : null,
          IsResidential: (_ref10 = this.isResidential) != null ? _ref10 : null,
          IsThirdPartyAcct: (_ref11 = this.isThirdPartyAcct) != null ? _ref11 : null,
          ThirdPartyCarrier: (_ref12 = this.thirdPartyCarrier) != null ? _ref12 : null,
          IsPackagesReload: (_ref13 = this.isPackagesReload) != null ? _ref13 : null,
          IsDefaultRequest: (_ref14 = this.isDefaultRequest) != null ? _ref14 : null,
          Currency: (_ref15 = this.currency) != null ? _ref15 : null,
          TransactionFxRate: (_ref16 = this.tranFxRate) != null ? _ref16 : null,
          Subsidiary: (_ref17 = this.subsidiary) != null ? _ref17 : null,
          TestId: (_ref18 = this.testId) != null ? _ref18 : null,
          OverrideShippingCost: (_ref19 = this.overrideShippingCost) != null ? _ref19 : null,
          IsDynamicScriptingRequest: (_ref20 = this.isDynamicScriptingRequest) != null ? _ref20 : null,
          Packages: (function() {
            var _i, _len, _ref21, _results;
            _ref21 = this.packages;
            _results = [];
            for (_i = 0, _len = _ref21.length; _i < _len; _i++) {
              pkg = _ref21[_i];
              _results.push(pkg.toXML());
            }
            return _results;
          }).call(this),
          Items: (function() {
            var _i, _len, _ref21, _results;
            _ref21 = this.items;
            _results = [];
            for (_i = 0, _len = _ref21.length; _i < _len; _i++) {
              item = _ref21[_i];
              _results.push(item.toXML());
            }
            return _results;
          }).call(this)
        }
      };
    };

    return RatesRequest;

  })();

  ShipPackage = (function() {

    function ShipPackage(params) {
      if (params == null) {
        params = {};
      }
      this.number = params.number;
      this.length = params.length;
      this.width = params.width;
      this.height = params.height;
      this.weight = params.weight;
      this.type = params.type;
      this.insuredValue = params.insuredValue;
      this.signatureOption = params.signatureOption;
    }

    ShipPackage.prototype.toXML = function() {
      var _ref, _ref1, _ref2, _ref3, _ref4, _ref5, _ref6, _ref7;
      return {
        Package: {
          PackageNumber: (_ref = this.number) != null ? _ref : null,
          PackageLength: (_ref1 = this.length) != null ? _ref1 : null,
          PackageWidth: (_ref2 = this.width) != null ? _ref2 : null,
          PackageHeight: (_ref3 = this.height) != null ? _ref3 : null,
          PackageWeight: (_ref4 = this.weight) != null ? _ref4 : null,
          PackageType: (_ref5 = this.type) != null ? _ref5 : null,
          PackageInsuredValue: (_ref6 = this.insuredValue) != null ? _ref6 : null,
          PackageSignatureOption: (_ref7 = this.signatureOption) != null ? _ref7 : null
        }
      };
    };

    return ShipPackage;

  })();

  ShipItem = (function() {

    function ShipItem(params) {
      if (params == null) {
        params = {};
      }
      this.quantity = params.quantity;
      this.amount = params.amount;
      this.weight = params.weight;
      this.location = params.location;
      this.key = params.key;
      this.units = params.units;
      this.type = params.type;
      this.shipAddrKey = params.shipAddrKey;
      this.shipAddr1 = params.shipAddr1;
      this.shipAddr2 = params.shipAddr2;
      this.shipCity = params.shipCity;
      this.shipState = params.shipState;
      this.shipZip = params.shipZip;
      this.shipCountry = params.shipCountry;
      this.shipIsResidential = params.shipIsResidential;
      this.shipMethKey = params.shipMethKey;
    }

    ShipItem.prototype.cloneAddr = function() {
      var addr, item, items, k, v, _i, _len, _results;
      items = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      addr = {
        shipAddrKey: this.shipAddrKey,
        shipAddr1: this.shipAddr1,
        shipAddr2: this.shipAddr2,
        shipCity: this.shipCity,
        shipState: this.shipState,
        shipZip: this.shipZip,
        shipCountry: this.shipCountry,
        shipIsResidential: this.shipIsResidential,
        shipMethKey: this.shipMethKey
      };
      if (!(items.length > 0)) {
        return addr;
      }
      _results = [];
      for (_i = 0, _len = items.length; _i < _len; _i++) {
        item = items[_i];
        _results.push((function() {
          var _results1;
          _results1 = [];
          for (k in addr) {
            v = addr[k];
            _results1.push(item[k] = v);
          }
          return _results1;
        })());
      }
      return _results;
    };

    ShipItem.prototype.toXML = function() {
      var _ref, _ref1, _ref10, _ref11, _ref12, _ref13, _ref14, _ref15, _ref2, _ref3, _ref4, _ref5, _ref6, _ref7, _ref8, _ref9;
      return {
        Item: {
          ItemQuantity: (_ref = this.quantity) != null ? _ref : null,
          ItemAmount: (_ref1 = this.amount) != null ? _ref1 : null,
          ItemWeight: (_ref2 = this.weight) != null ? _ref2 : null,
          ItemKey: (_ref3 = this.key) != null ? _ref3 : null,
          ItemLocation: (_ref4 = this.location) != null ? _ref4 : null,
          ItemUnits: (_ref5 = this.units) != null ? _ref5 : null,
          ItemType: (_ref6 = this.type) != null ? _ref6 : null,
          ItemShipAddrKey: (_ref7 = this.shipAddrKey) != null ? _ref7 : null,
          ItemShipAddr1: (_ref8 = this.shipAddr1) != null ? _ref8 : null,
          ItemShipAddr2: (_ref9 = this.shipAddr2) != null ? _ref9 : null,
          ItemShipCity: (_ref10 = this.shipCity) != null ? _ref10 : null,
          ItemShipState: (_ref11 = this.shipState) != null ? _ref11 : null,
          ItemShipZip: (_ref12 = this.shipZip) != null ? _ref12 : null,
          ItemShipCountry: (_ref13 = this.shipCountry) != null ? _ref13 : null,
          ItemShipIsResidential: (_ref14 = this.shipIsResidential) != null ? _ref14 : null,
          ItemShipMethKey: (_ref15 = this.shipMethKey) != null ? _ref15 : null
        }
      };
    };

    return ShipItem;

  })();

  exports.extend = function(client) {
    client.prototype.getShippingRates = function(ratesReq, cb) {
      var opts, payload;
      if (typeof ratesReq === 'object') {
        if (ratesReq.RatesRequest) {
          payload = xml.render(ratesReq);
        } else {
          if (ratesReq.toXML == null) {
            ratesReq = new RatesRequest(ratesReq);
          }
          payload = xml.render(ratesReq.toXML());
        }
      } else {
        payload = ratesReq;
      }
      opts = {
        method: 'POST',
        path: '/app/common/shipping/dynshippingxml.nl'
      };
      return this.jsonr('getShippingRates', [payload], opts, cb);
    };
    client.prototype.getItemShipInfo = function(shipMethod, cb) {
      var opts, payload,
        _this = this;
      payload = xml.render(ItemShipRequest(shipMethod));
      console.log(payload);
      opts = {
        path: '/app/accounting/transactions/dynitemship.nl'
      };
      return this.jsonr('getItemShipInfo', [payload], opts, function(res) {
        if (res.result) {
          return xml.parse(res.result, function(err, data) {
            if (err) {
              throw err;
            }
            return cb(data, res);
          });
        } else {
          return cb(null, res);
        }
      });
    };
    client.prototype.getTaxItem = function(entityId, state, zip, country, cb) {
      var opts, payload;
      payload = xml.render(ShipTaxItemRequest(entityId, state, zip, country));
      opts = {
        path: '/app/common/shipping/dynshiptaxitem.nl'
      };
      return this.jsonr('getTaxItem', [payload], opts, cb);
    };
    return {
      RatesRequest: RatesRequest,
      Package: ShipPackage,
      Item: ShipItem
    };
  };

}).call(this);
