xmnls = module.exports = 
  actSched: 'urn:scheduling_2012_1.activities.webservices.netsuite.com'
  demandPlanning: 'urn:demandplanning_2012_1.transactions.webservices.netsuite.com'
  docFileCab: 'urn:filecabinet_2012_1.documents.webservices.netsuite.com'
  generalComm: 'urn:communication_2012_1.general.webservices.netsuite.com'
  listAcct: 'urn:accounting_2012_1.lists.webservices.netsuite.com'
  listEmp: 'urn:employees_2012_1.lists.webservices.netsuite.com'
  listMkt: 'urn:marketing_2012_1.lists.webservices.netsuite.com'
  listRel: 'urn:relationships_2012_1.lists.webservices.netsuite.com'
  listSite: 'urn:website_2012_1.lists.webservices.netsuite.com'
  listSupport: 'urn:support_2012_1.lists.webservices.netsuite.com'
  platformCommon: 'urn:common_2012_1.platform.webservices.netsuite.com'
  platformCore: 'urn:core_2012_1.platform.webservices.netsuite.com'
  platformFaults: 'urn:faults_2012_1.platform.webservices.netsuite.com'
  platformMsgs: 'urn:messages_2012_1.platform.webservices.netsuite.com'
  setupCustom: 'urn:customization_2012_1.setup.webservices.netsuite.com'
  soap: 'http://schemas.xmlsoap.org/wsdl/soap/'
  tns: 'urn:platform_2012_1.webservices.netsuite.com'
  tranBank: 'urn:bank_2012_1.transactions.webservices.netsuite.com'
  tranCust: 'urn:customers_2012_1.transactions.webservices.netsuite.com'
  tranEmp: 'urn:employees_2012_1.transactions.webservices.netsuite.com'
  tranFin: 'urn:financial_2012_1.transactions.webservices.netsuite.com'
  tranGeneral: 'urn:general_2012_1.transactions.webservices.netsuite.com'
  tranInvt: 'urn:inventory_2012_1.transactions.webservices.netsuite.com'
  tranPurch: 'urn:purchases_2012_1.transactions.webservices.netsuite.com'
  tranSales: 'urn:sales_2012_1.transactions.webservices.netsuite.com'
  wsdl: 'http://schemas.xmlsoap.org/wsdl/'
  xsd: 'http://www.w3.org/2001/XMLSchema'
  actSchedTyp: 'urn:types.scheduling_2012_1.activities.webservices.netsuite.com'
  demandPlanningTyp: 'urn:types.demandplanning_2012_1.transactions.webservices.netsuite.com'
  docFileCabTyp: 'urn:types.filecabinet_2012_1.documents.webservices.netsuite.com'
  generalCommTyp: 'urn:types.communication_2012_1.general.webservices.netsuite.com'
  listAcctTyp: 'urn:types.accounting_2012_1.lists.webservices.netsuite.com'
  listEmpTyp: 'urn:types.employees_2012_1.lists.webservices.netsuite.com'
  listMktTyp: 'urn:types.marketing_2012_1.lists.webservices.netsuite.com'
  listRelTyp: 'urn:types.relationships_2012_1.lists.webservices.netsuite.com'
  listSiteTyp: 'urn:types.website_2012_1.lists.webservices.netsuite.com'
  listSupportTyp: 'urn:types.support_2012_1.lists.webservices.netsuite.com'
  platformCommonTyp: 'urn:types.common_2012_1.platform.webservices.netsuite.com'
  platformCoreTyp: 'urn:types.core_2012_1.platform.webservices.netsuite.com'
  platformFaultTyp: 'urn:types.faults_2012_1.platform.webservices.netsuite.com'
  setupCustomTyp: 'urn:types.customization_2012_1.setup.webservices.netsuite.com'
  tranBankTyp: 'urn:types.bank_2012_1.transactions.webservices.netsuite.com'
  tranCustomersTyp: 'urn:types.customers_2012_1.transactions.webservices.netsuite.com'
  tranCustTyp: 'urn:types.customers_2012_1.transactions.webservices.netsuite.com'
  tranEmployeesTyp: 'urn:types.employees_2012_1.transactions.webservices.netsuite.com'
  tranEmpTyp: 'urn:types.employees_2012_1.transactions.webservices.netsuite.com'
  tranFinancialTyp: 'urn:types.financial_2012_1.transactions.webservices.netsuite.com'
  tranFinTyp: 'urn:types.financial_2012_1.transactions.webservices.netsuite.com'
  tranInvtTyp: 'urn:types.inventory_2012_1.transactions.webservices.netsuite.com'
  tranPurchTyp: 'urn:types.purchases_2012_1.transactions.webservices.netsuite.com'
  tranSalesTyp: 'urn:types.sales_2012_1.transactions.webservices.netsuite.com'
  # Complex Type -> Namespace map
  Account: @listAcct
  AccountSearch: @listAcct
  AccountSearchAdvanced: @listAcct
  AccountSearchBasic: @platformCommon
  AccountSearchRow: @listAcct
  AccountSearchRowBasic: @platformCommon
  AccountTranslationList: @listAcct
  AccountingPeriod: @listAcct
  AccountingPeriodSearch: @listAcct
  AccountingPeriodSearchAdvanced: @listAcct
  AccountingPeriodSearchBasic: @platformCommon
  AccountingPeriodSearchRow: @listAcct
  AccountingPeriodSearchRowBasic: @platformCommon
  AddListRequest: @platformMsgs
  AddListResponse: @platformMsgs
  AddRequest: @platformMsgs
  AddResponse: @platformMsgs
  AppDefinition: @setupCustom
  AppDefinitionPackages: @setupCustom
  AppDefinitionPackagesList: @setupCustom
  AppDefinitionSearch: @setupCustom
  AppDefinitionSearchAdvanced: @setupCustom
  AppDefinitionSearchBasic: @platformCommon
  AppDefinitionSearchRow: @setupCustom
  AppDefinitionSearchRowBasic: @platformCommon
  AppPackage: @setupCustom
  AppPackageSearch: @setupCustom
  AppPackageSearchAdvanced: @setupCustom
  AppPackageSearchBasic: @platformCommon
  AppPackageSearchRow: @setupCustom
  AppPackageSearchRowBasic: @platformCommon
  ApplicationInfo: @platformMsgs
  AssemblyBuild: @tranInvt
  AssemblyComponent: @tranInvt
  AssemblyComponentList: @tranInvt
  AssemblyItem: @listAcct
  AssemblyUnbuild: @tranInvt
  AsyncAddListRequest: @platformMsgs
  AsyncAddListResult: @platformMsgs
  AsyncDeleteListRequest: @platformMsgs
  AsyncDeleteListResult: @platformMsgs
  AsyncFault: @platformFaults
  AsyncGetListRequest: @platformMsgs
  AsyncGetListResult: @platformMsgs
  AsyncInitializeListRequest: @platformMsgs
  AsyncInitializeListResult: @platformMsgs
  AsyncResult: @platformMsgs
  AsyncSearchRequest: @platformMsgs
  AsyncSearchResult: @platformMsgs
  AsyncStatusResponse: @platformMsgs
  AsyncStatusResult: @platformCore
  AsyncUpdateListRequest: @platformMsgs
  AsyncUpdateListResult: @platformMsgs
  AsyncUpsertListRequest: @platformMsgs
  AsyncUpsertListResult: @platformMsgs
  AttachBasicReference: @platformCore
  AttachContactReference: @platformCore
  AttachReference: @platformCore
  AttachRequest: @platformMsgs
  AttachResponse: @platformMsgs
  BaseRef: @platformCore
  BaseRefList: @platformCore
  BillAddress: @platformCommon
  BillingRates: @listAcct
  BillingRatesMatrix: @listAcct
  Bin: @listAcct
  BinSearch: @listAcct
  BinSearchAdvanced: @listAcct
  BinSearchBasic: @platformCommon
  BinSearchRow: @listAcct
  BinSearchRowBasic: @platformCommon
  BinTransfer: @tranInvt
  BinTransferInventory: @tranInvt
  BinTransferInventoryList: @tranInvt
  BinWorksheet: @tranInvt
  BinWorksheetItem: @tranInvt
  BinWorksheetItemList: @tranInvt
  BooleanCustomFieldRef: @platformCore
  Budget: @tranFin
  BudgetCategory: @listAcct
  BudgetExchangeRate: @platformCore
  BudgetExchangeRateFilter: @platformCore
  BudgetExchangeRateList: @platformCore
  BudgetSearch: @tranFin
  BudgetSearchAdvanced: @tranFin
  BudgetSearchBasic: @platformCommon
  BudgetSearchRow: @tranFin
  BudgetSearchRowBasic: @platformCommon
  CalendarEvent: @actSched
  CalendarEventAttendee: @actSched
  CalendarEventAttendeeList: @actSched
  CalendarEventResource: @actSched
  CalendarEventResourceList: @actSched
  CalendarEventSearch: @actSched
  CalendarEventSearchAdvanced: @actSched
  CalendarEventSearchBasic: @platformCommon
  CalendarEventSearchRow: @actSched
  CalendarEventSearchRowBasic: @platformCommon
  CalendarEventTimeItemList: @actSched
  Campaign: @listMkt
  CampaignAudience: @listMkt
  CampaignCategory: @listMkt
  CampaignChannel: @listMkt
  CampaignDirectMail: @listMkt
  CampaignDirectMailList: @listMkt
  CampaignEmail: @listMkt
  CampaignEmailList: @listMkt
  CampaignEvent: @listMkt
  CampaignEventList: @listMkt
  CampaignEventResponse: @listMkt
  CampaignEventResponseList: @listMkt
  CampaignFamily: @listMkt
  CampaignOffer: @listMkt
  CampaignResponseResponses: @listMkt
  CampaignResponseResponsesList: @listMkt
  CampaignSearch: @listMkt
  CampaignSearchAdvanced: @listMkt
  CampaignSearchBasic: @platformCommon
  CampaignSearchEngine: @listMkt
  CampaignSearchRow: @listMkt
  CampaignSearchRowBasic: @platformCommon
  CampaignSubscription: @listMkt
  CampaignVertical: @listMkt
  CashRefund: @tranCust
  CashRefundItem: @tranCust
  CashRefundItemList: @tranCust
  CashRefundPartnersList: @tranCust
  CashRefundSalesTeam: @tranCust
  CashRefundSalesTeamList: @tranCust
  CashSale: @tranSales
  CashSaleExpCost: @tranSales
  CashSaleExpCostList: @tranSales
  CashSaleItem: @tranSales
  CashSaleItemCost: @tranSales
  CashSaleItemCostList: @tranSales
  CashSaleItemList: @tranSales
  CashSalePartnersList: @tranSales
  CashSaleSalesTeam: @tranSales
  CashSaleSalesTeamList: @tranSales
  CashSaleShipGroupList: @tranSales
  CashSaleTime: @tranSales
  CashSaleTimeList: @tranSales
  CategoryList: @listRel
  ChangePasswordOrEmailCredentials: @platformCore
  ChangePasswordOrEmailRequest: @platformMsgs
  ChangePasswordOrEmailResponse: @platformMsgs
  Check: @tranBank
  CheckAsyncStatusRequest: @platformMsgs
  CheckExpense: @tranBank
  CheckExpenseList: @tranBank
  CheckItem: @tranBank
  CheckItemList: @tranBank
  CheckLandedCostList: @tranBank
  ClassTranslation: @listAcct
  ClassTranslationList: @listAcct
  Classification: @listAcct
  ClassificationSearch: @listAcct
  ClassificationSearchAdvanced: @listAcct
  ClassificationSearchBasic: @platformCommon
  ClassificationSearchRow: @listAcct
  ClassificationSearchRowBasic: @platformCommon
  ConsolidatedExchangeRate: @platformCore
  ConsolidatedExchangeRateFilter: @platformCore
  ConsolidatedExchangeRateList: @platformCore
  Contact: @listRel
  ContactAccessRoles: @listRel
  ContactAccessRolesList: @listRel
  ContactAddressbook: @listRel
  ContactAddressbookList: @listRel
  ContactCategory: @listAcct
  ContactCategorySearch: @listAcct
  ContactCategorySearchAdvanced: @listAcct
  ContactCategorySearchBasic: @platformCommon
  ContactCategorySearchRow: @listAcct
  ContactCategorySearchRowBasic: @platformCommon
  ContactRole: @listAcct
  ContactRoleSearch: @listAcct
  ContactRoleSearchAdvanced: @listAcct
  ContactRoleSearchBasic: @platformCommon
  ContactRoleSearchRow: @listAcct
  ContactRoleSearchRowBasic: @platformCommon
  ContactSearch: @listRel
  ContactSearchAdvanced: @listRel
  ContactSearchBasic: @platformCommon
  ContactSearchRow: @listRel
  ContactSearchRowBasic: @platformCommon
  CostCategory: @listAcct
  CreditMemo: @tranCust
  CreditMemoApply: @tranCust
  CreditMemoApplyList: @tranCust
  CreditMemoItem: @tranCust
  CreditMemoItemList: @tranCust
  CreditMemoPartnersList: @tranCust
  CreditMemoSalesTeam: @tranCust
  CreditMemoSalesTeamList: @tranCust
  CrmCustomField: @setupCustom
  CrmCustomFieldFilter: @setupCustom
  CrmCustomFieldFilterList: @setupCustom
  Currency: @listAcct
  CustomFieldDepartmentAccess: @setupCustom
  CustomFieldDepartmentAccessList: @setupCustom
  CustomFieldList: @platformCore
  CustomFieldRef: @platformCore
  CustomFieldRoleAccess: @setupCustom
  CustomFieldRoleAccessList: @setupCustom
  CustomFieldSubAccess: @setupCustom
  CustomFieldSubAccessList: @setupCustom
  CustomFieldTranslations: @setupCustom
  CustomFieldTranslationsList: @setupCustom
  CustomList: @setupCustom
  CustomListCustomValue: @setupCustom
  CustomListCustomValueList: @setupCustom
  CustomListSearch: @setupCustom
  CustomListSearchBasic: @platformCommon
  CustomListSearchRow: @setupCustom
  CustomListSearchRowBasic: @platformCommon
  CustomListTranslations: @setupCustom
  CustomListTranslationsList: @setupCustom
  CustomRecord: @setupCustom
  CustomRecordCustomField: @setupCustom
  CustomRecordCustomFieldFilter: @setupCustom
  CustomRecordCustomFieldFilterList: @setupCustom
  CustomRecordRef: @platformCore
  CustomRecordSearch: @setupCustom
  CustomRecordSearchAdvanced: @setupCustom
  CustomRecordSearchBasic: @platformCommon
  CustomRecordSearchRow: @setupCustom
  CustomRecordSearchRowBasic: @platformCommon
  CustomRecordType: @setupCustom
  CustomRecordTypeChildren: @setupCustom
  CustomRecordTypeChildrenList: @setupCustom
  CustomRecordTypeFieldList: @setupCustom
  CustomRecordTypeForms: @setupCustom
  CustomRecordTypeFormsList: @setupCustom
  CustomRecordTypeLinks: @setupCustom
  CustomRecordTypeLinksList: @setupCustom
  CustomRecordTypeManagers: @setupCustom
  CustomRecordTypeManagersList: @setupCustom
  CustomRecordTypeOnlineForms: @setupCustom
  CustomRecordTypeOnlineFormsList: @setupCustom
  CustomRecordTypeParents: @setupCustom
  CustomRecordTypeParentsList: @setupCustom
  CustomRecordTypePermissions: @setupCustom
  CustomRecordTypePermissionsList: @setupCustom
  CustomRecordTypeSublists: @setupCustom
  CustomRecordTypeSublistsList: @setupCustom
  CustomRecordTypeTabs: @setupCustom
  CustomRecordTypeTabsList: @setupCustom
  CustomRecordTypeTranslations: @setupCustom
  CustomRecordTypeTranslationsList: @setupCustom
  Customer: @listRel
  CustomerAddressbook: @listRel
  CustomerAddressbookList: @listRel
  CustomerCategory: @listAcct
  CustomerCategorySearch: @listAcct
  CustomerCategorySearchAdvanced: @listAcct
  CustomerCategorySearchBasic: @platformCommon
  CustomerCategorySearchRow: @listAcct
  CustomerCategorySearchRowBasic: @platformCommon
  CustomerCreditCards: @listRel
  CustomerCreditCardsList: @listRel
  CustomerCurrency: @listRel
  CustomerCurrencyList: @listRel
  CustomerDeposit: @tranCust
  CustomerDepositApply: @tranCust
  CustomerDepositApplyList: @tranCust
  CustomerDownload: @listRel
  CustomerDownloadList: @listRel
  CustomerGroupPricing: @listRel
  CustomerGroupPricingList: @listRel
  CustomerItemPricing: @listRel
  CustomerItemPricingList: @listRel
  CustomerMessage: @listAcct
  CustomerMessageSearch: @listAcct
  CustomerMessageSearchAdvanced: @listAcct
  CustomerMessageSearchBasic: @platformCommon
  CustomerMessageSearchRow: @listAcct
  CustomerMessageSearchRowBasic: @platformCommon
  CustomerPartnersList: @listRel
  CustomerPayment: @tranCust
  CustomerPaymentApply: @tranCust
  CustomerPaymentApplyList: @tranCust
  CustomerPaymentCredit: @tranCust
  CustomerPaymentCreditList: @tranCust
  CustomerPaymentDeposit: @tranCust
  CustomerPaymentDepositList: @tranCust
  CustomerRefund: @tranCust
  CustomerRefundApply: @tranCust
  CustomerRefundApplyList: @tranCust
  CustomerRefundDeposit: @tranCust
  CustomerRefundDepositList: @tranCust
  CustomerSalesTeamList: @listRel
  CustomerSearch: @listRel
  CustomerSearchAdvanced: @listRel
  CustomerSearchBasic: @platformCommon
  CustomerSearchRow: @listRel
  CustomerSearchRowBasic: @platformCommon
  CustomerStatus: @listRel
  CustomerStatusSearch: @listRel
  CustomerStatusSearchAdvanced: @listRel
  CustomerStatusSearchBasic: @platformCommon
  CustomerStatusSearchRow: @listRel
  CustomerStatusSearchRowBasic: @platformCommon
  CustomizationRef: @platformCore
  CustomizationRefList: @platformCore
  CustomizationType: @platformCore
  DateCustomFieldRef: @platformCore
  DeleteListRequest: @platformMsgs
  DeleteListResponse: @platformMsgs
  DeleteRequest: @platformMsgs
  DeleteResponse: @platformMsgs
  DeletedRecord: @platformCore
  DeletedRecordList: @platformCore
  Department: @listAcct
  DepartmentSearch: @listAcct
  DepartmentSearchAdvanced: @listAcct
  DepartmentSearchBasic: @platformCommon
  DepartmentSearchRow: @listAcct
  DepartmentSearchRowBasic: @platformCommon
  DepositApplication: @tranCust
  DepositApplicationApply: @tranCust
  DepositApplicationApplyList: @tranCust
  DescriptionItem: @listAcct
  DetachBasicReference: @platformCore
  DetachReference: @platformCore
  DetachRequest: @platformMsgs
  DetachResponse: @platformMsgs
  DiscountItem: @listAcct
  DocumentInfo: @platformMsgs
  DoubleCustomFieldRef: @platformCore
  DownloadItem: @listAcct
  Duration: @platformCore
  EmailEmployeesList: @listSupport
  Employee: @listEmp
  EmployeeAccruedTime: @listEmp
  EmployeeAccruedTimeList: @listEmp
  EmployeeAddressbook: @listEmp
  EmployeeAddressbookList: @listEmp
  EmployeeCompanyContribution: @listEmp
  EmployeeCompanyContributionList: @listEmp
  EmployeeDeduction: @listEmp
  EmployeeDeductionList: @listEmp
  EmployeeDirectDeposit: @listEmp
  EmployeeDirectDepositList: @listEmp
  EmployeeEarning: @listEmp
  EmployeeEarningList: @listEmp
  EmployeeEmergencyContact: @listEmp
  EmployeeEmergencyContactList: @listEmp
  EmployeeHrEducation: @listEmp
  EmployeeHrEducationList: @listEmp
  EmployeeRoles: @listEmp
  EmployeeRolesList: @listEmp
  EmployeeSearch: @listEmp
  EmployeeSearchAdvanced: @listEmp
  EmployeeSearchBasic: @platformCommon
  EmployeeSearchRow: @listEmp
  EmployeeSearchRowBasic: @platformCommon
  EmployeeSubscriptions: @listEmp
  EmployeeSubscriptionsList: @listEmp
  EntityCustomField: @setupCustom
  EntityCustomFieldFilter: @setupCustom
  EntityCustomFieldFilterList: @setupCustom
  EntityGroup: @listRel
  EntityGroupSearch: @listRel
  EntityGroupSearchAdvanced: @listRel
  EntityGroupSearchBasic: @platformCommon
  EntityGroupSearchRow: @listRel
  EntityGroupSearchRowBasic: @platformCommon
  EntitySearchBasic: @platformCommon
  EntitySearchRowBasic: @platformCommon
  Estimate: @tranSales
  EstimateItem: @tranSales
  EstimateItemList: @tranSales
  EstimatePartnersList: @tranSales
  EstimateSalesTeam: @tranSales
  EstimateSalesTeamList: @tranSales
  EstimateShipGroupList: @tranSales
  ExceededRecordCountFault: @platformFaults
  ExceededRequestLimitFault: @platformFaults
  ExceededRequestSizeFault: @platformFaults
  ExceededUsageLimitFault: @platformFaults
  ExclusionDateList: @actSched
  ExpenseCategory: @listAcct
  ExpenseCategorySearch: @listAcct
  ExpenseCategorySearchAdvanced: @listAcct
  ExpenseCategorySearchBasic: @platformCommon
  ExpenseCategorySearchRow: @listAcct
  ExpenseCategorySearchRowBasic: @platformCommon
  ExpenseReport: @tranEmp
  ExpenseReportExpense: @tranEmp
  ExpenseReportExpenseList: @tranEmp
  File: @docFileCab
  FileSearch: @docFileCab
  FileSearchAdvanced: @docFileCab
  FileSearchBasic: @platformCommon
  FileSearchRow: @docFileCab
  FileSearchRowBasic: @platformCommon
  FileSiteCategory: @docFileCab
  FileSiteCategoryList: @docFileCab
  FldFilterSelList: @setupCustom
  Folder: @docFileCab
  FolderSearch: @docFileCab
  FolderSearchAdvanced: @docFileCab
  FolderSearchBasic: @platformCommon
  FolderSearchRow: @docFileCab
  FolderSearchRowBasic: @platformCommon
  GetAllRecord: @platformCore
  GetAllRequest: @platformMsgs
  GetAllResponse: @platformMsgs
  GetAllResult: @platformCore
  GetAsyncResultRequest: @platformMsgs
  GetAsyncResultResponse: @platformMsgs
  GetBudgetExchangeRateRequest: @platformMsgs
  GetBudgetExchangeRateResponse: @platformMsgs
  GetBudgetExchangeRateResult: @platformCore
  GetConsolidatedExchangeRateRequest: @platformMsgs
  GetConsolidatedExchangeRateResponse: @platformMsgs
  GetConsolidatedExchangeRateResult: @platformCore
  GetCustomizationIdRequest: @platformMsgs
  GetCustomizationIdResponse: @platformMsgs
  GetCustomizationIdResult: @platformCore
  GetDeletedFilter: @platformCore
  GetDeletedRequest: @platformMsgs
  GetDeletedResponse: @platformMsgs
  GetDeletedResult: @platformCore
  GetItemAvailabilityRequest: @platformMsgs
  GetItemAvailabilityResponse: @platformMsgs
  GetItemAvailabilityResult: @platformCore
  GetListRequest: @platformMsgs
  GetListResponse: @platformMsgs
  GetPostingTransactionSummaryRequest: @platformMsgs
  GetPostingTransactionSummaryResponse: @platformMsgs
  GetPostingTransactionSummaryResult: @platformCore
  GetRequest: @platformMsgs
  GetResponse: @platformMsgs
  GetSavedSearchRecord: @platformCore
  GetSavedSearchRequest: @platformMsgs
  GetSavedSearchResponse: @platformMsgs
  GetSavedSearchResult: @platformCore
  GetSelectFilterByFieldValue: @platformCore
  GetSelectFilterByFieldValueList: @platformCore
  GetSelectValueFieldDescription: @platformCore
  GetSelectValueFilter: @platformCore
  GetSelectValueResult: @platformCore
  GetServerTimeRequest: @platformMsgs
  GetServerTimeResponse: @platformMsgs
  GetServerTimeResult: @platformCore
  GiftCertRedemption: @tranSales
  GiftCertRedemptionList: @tranSales
  GiftCertificate: @listAcct
  GiftCertificateItem: @listAcct
  GiftCertificateItemAuthCodes: @listAcct
  GiftCertificateItemAuthCodesList: @listAcct
  GiftCertificateSearch: @listAcct
  GiftCertificateSearchAdvanced: @listAcct
  GiftCertificateSearchBasic: @platformCommon
  GiftCertificateSearchRow: @listAcct
  GiftCertificateSearchRowBasic: @platformCommon
  GroupMemberSearchBasic: @platformCommon
  InitializeAuxRef: @platformCore
  InitializeListRequest: @platformMsgs
  InitializeListResponse: @platformMsgs
  InitializeRecord: @platformCore
  InitializeRef: @platformCore
  InitializeRequest: @platformMsgs
  InitializeResponse: @platformMsgs
  InsufficientPermissionFault: @platformFaults
  InterCompanyJournalEntry: @tranGeneral
  InterCompanyJournalEntryLine: @tranGeneral
  InterCompanyJournalEntryLineList: @tranGeneral
  InterCompanyTransferOrder: @tranInvt
  InterCompanyTransferOrderItem: @tranInvt
  InterCompanyTransferOrderItemList: @tranInvt
  InvalidAccountFault: @platformFaults
  InvalidCredentialsFault: @platformFaults
  InvalidSessionFault: @platformFaults
  InvalidVersionFault: @platformFaults
  InventoryAdjustment: @tranInvt
  InventoryAdjustmentInventory: @tranInvt
  InventoryAdjustmentInventoryList: @tranInvt
  InventoryAssignment: @platformCommon
  InventoryAssignmentList: @platformCommon
  InventoryDetail: @platformCommon
  InventoryDetailSearchBasic: @platformCommon
  InventoryDetailSearchRowBasic: @platformCommon
  InventoryItem: @listAcct
  InventoryItemBinNumber: @listAcct
  InventoryItemBinNumberList: @listAcct
  InventoryItemLocations: @listAcct
  InventoryItemLocationsList: @listAcct
  InventoryNumber: @listAcct
  InventoryNumberLocations: @listAcct
  InventoryNumberLocationsList: @listAcct
  InventoryNumberSearch: @listAcct
  InventoryNumberSearchAdvanced: @listAcct
  InventoryNumberSearchBasic: @platformCommon
  InventoryNumberSearchRow: @listAcct
  InventoryNumberSearchRowBasic: @platformCommon
  InventoryTransfer: @tranInvt
  InventoryTransferInventory: @tranInvt
  InventoryTransferInventoryList: @tranInvt
  Invoice: @tranSales
  InvoiceExpCost: @tranSales
  InvoiceExpCostList: @tranSales
  InvoiceItem: @tranSales
  InvoiceItemCost: @tranSales
  InvoiceItemCostList: @tranSales
  InvoiceItemList: @tranSales
  InvoicePartnersList: @tranSales
  InvoiceSalesTeam: @tranSales
  InvoiceSalesTeamList: @tranSales
  InvoiceShipGroupList: @tranSales
  InvoiceTime: @tranSales
  InvoiceTimeList: @tranSales
  Issue: @listSupport
  IssueSearch: @listSupport
  IssueSearchAdvanced: @listSupport
  IssueSearchBasic: @platformCommon
  IssueSearchRow: @listSupport
  IssueSearchRowBasic: @platformCommon
  IssueVersion: @listSupport
  IssueVersionList: @listSupport
  ItemAvailability: @platformCore
  ItemAvailabilityFilter: @platformCore
  ItemAvailabilityList: @platformCore
  ItemCustomField: @setupCustom
  ItemCustomFieldFilter: @setupCustom
  ItemCustomFieldFilterList: @setupCustom
  ItemFulfillment: @tranSales
  ItemFulfillmentItem: @tranSales
  ItemFulfillmentItemList: @tranSales
  ItemFulfillmentPackage: @tranSales
  ItemFulfillmentPackageFedEx: @tranSales
  ItemFulfillmentPackageFedExList: @tranSales
  ItemFulfillmentPackageList: @tranSales
  ItemFulfillmentPackageUps: @tranSales
  ItemFulfillmentPackageUpsList: @tranSales
  ItemFulfillmentPackageUsps: @tranSales
  ItemFulfillmentPackageUspsList: @tranSales
  ItemFulfillmentShipGroupList: @tranSales
  ItemMember: @listAcct
  ItemMemberList: @listAcct
  ItemNumberCustomField: @setupCustom
  ItemNumberCustomFieldFilter: @setupCustom
  ItemNumberCustomFieldFilterList: @setupCustom
  ItemOptionCustomField: @setupCustom
  ItemOptionCustomFieldFilter: @setupCustom
  ItemOptionCustomFieldFilterList: @setupCustom
  ItemOptionsList: @listAcct
  ItemReceipt: @tranPurch
  ItemReceiptExpense: @tranPurch
  ItemReceiptExpenseList: @tranPurch
  ItemReceiptItem: @tranPurch
  ItemReceiptItemList: @tranPurch
  ItemSearch: @listAcct
  ItemSearchAdvanced: @listAcct
  ItemSearchBasic: @platformCommon
  ItemSearchRow: @listAcct
  ItemSearchRowBasic: @platformCommon
  ItemVendor: @listAcct
  ItemVendorList: @listAcct
  ItemsList: @setupCustom
  Job: @listRel
  JobAddressbook: @listRel
  JobAddressbookList: @listRel
  JobCreditCards: @listRel
  JobCreditCardsList: @listRel
  JobMilestones: @listRel
  JobMilestonesList: @listRel
  JobResources: @listRel
  JobResourcesList: @listRel
  JobSearch: @listRel
  JobSearchAdvanced: @listRel
  JobSearchBasic: @platformCommon
  JobSearchRow: @listRel
  JobSearchRowBasic: @platformCommon
  JobStatus: @listRel
  JobStatusSearch: @listRel
  JobStatusSearchAdvanced: @listRel
  JobStatusSearchBasic: @platformCommon
  JobStatusSearchRow: @listRel
  JobStatusSearchRowBasic: @platformCommon
  JobType: @listRel
  JobTypeSearch: @listRel
  JobTypeSearchAdvanced: @listRel
  JobTypeSearchBasic: @platformCommon
  JobTypeSearchRow: @listRel
  JobTypeSearchRowBasic: @platformCommon
  JournalEntry: @tranGeneral
  JournalEntryLine: @tranGeneral
  JournalEntryLineList: @tranGeneral
  KitItem: @listAcct
  LandedCost: @platformCommon
  LanguageValue: @setupCustom
  LanguageValueList: @setupCustom
  LeadSource: @listAcct
  ListOrRecordRef: @platformCore
  Location: @listAcct
  LocationSearch: @listAcct
  LocationSearchAdvanced: @listAcct
  LocationSearchBasic: @platformCommon
  LocationSearchRow: @listAcct
  LocationSearchRowBasic: @platformCommon
  LoginRequest: @platformMsgs
  LoginResponse: @platformMsgs
  LogoutRequest: @platformMsgs
  LogoutResponse: @platformMsgs
  LongCustomFieldRef: @platformCore
  LotNumberedAssemblyItem: @listAcct
  LotNumberedInventoryItem: @listAcct
  LotNumberedInventoryItemLocations: @listAcct
  LotNumberedInventoryItemLocationsList: @listAcct
  LotNumberedInventoryItemNumbers: @listAcct
  LotNumberedInventoryItemNumbersList: @listAcct
  MapSsoRequest: @platformMsgs
  MapSsoResponse: @platformMsgs
  MarkupItem: @listAcct
  MatrixOptionList: @listAcct
  Message: @generalComm
  MessageMediaItemList: @generalComm
  MessageSearch: @generalComm
  MessageSearchAdvanced: @generalComm
  MessageSearchBasic: @platformCommon
  MessageSearchRow: @generalComm
  MessageSearchRowBasic: @platformCommon
  MultiSelectCustomFieldRef: @platformCore
  Nexus: @listAcct
  NexusSearch: @listAcct
  NexusSearchAdvanced: @listAcct
  NexusSearchBasic: @platformCommon
  NexusSearchRow: @listAcct
  NexusSearchRowBasic: @platformCommon
  NonInventoryPurchaseItem: @listAcct
  NonInventoryResaleItem: @listAcct
  NonInventorySaleItem: @listAcct
  Note: @generalComm
  NoteSearch: @generalComm
  NoteSearchAdvanced: @generalComm
  NoteSearchBasic: @platformCommon
  NoteSearchRow: @generalComm
  NoteSearchRowBasic: @platformCommon
  NoteType: @listAcct
  NoteTypeSearch: @listAcct
  NoteTypeSearchAdvanced: @listAcct
  NoteTypeSearchBasic: @platformCommon
  NoteTypeSearchRow: @listAcct
  NoteTypeSearchRowBasic: @platformCommon
  NullField: @platformCore
  Opportunity: @tranSales
  OpportunityCompetitors: @tranSales
  OpportunityCompetitorsList: @tranSales
  OpportunityItem: @tranSales
  OpportunityItemList: @tranSales
  OpportunityPartnersList: @tranSales
  OpportunitySalesTeam: @tranSales
  OpportunitySalesTeamList: @tranSales
  OpportunitySearch: @tranSales
  OpportunitySearchAdvanced: @tranSales
  OpportunitySearchBasic: @platformCommon
  OpportunitySearchRow: @tranSales
  OpportunitySearchRowBasic: @platformCommon
  OriginatingLeadSearch: @listRel
  OriginatingLeadSearchBasic: @platformCommon
  OriginatingLeadSearchRow: @listRel
  OriginatingLeadSearchRowBasic: @platformCommon
  OtherChargePurchaseItem: @listAcct
  OtherChargeResaleItem: @listAcct
  OtherChargeSaleItem: @listAcct
  OtherCustomField: @setupCustom
  OtherCustomFieldFilter: @setupCustom
  OtherCustomFieldFilterList: @setupCustom
  OtherNameCategory: @listAcct
  OtherNameCategorySearch: @listAcct
  OtherNameCategorySearchAdvanced: @listAcct
  OtherNameCategorySearchBasic: @platformCommon
  OtherNameCategorySearchRow: @listAcct
  OtherNameCategorySearchRowBasic: @platformCommon
  Partner: @listRel
  PartnerAddressbook: @listRel
  PartnerAddressbookList: @listRel
  PartnerCategory: @listAcct
  PartnerCategorySearch: @listAcct
  PartnerCategorySearchAdvanced: @listAcct
  PartnerCategorySearchBasic: @platformCommon
  PartnerCategorySearchRow: @listAcct
  PartnerCategorySearchRowBasic: @platformCommon
  PartnerInfo: @platformMsgs
  PartnerPromoCode: @listRel
  PartnerPromoCodeList: @listRel
  PartnerSearch: @listRel
  PartnerSearchAdvanced: @listRel
  PartnerSearchBasic: @platformCommon
  PartnerSearchRow: @listRel
  PartnerSearchRowBasic: @platformCommon
  Partners: @platformCommon
  PartnersList: @tranInvt
  Passport: @platformCore
  PaymentItem: @listAcct
  PaymentMethod: @listAcct
  PaymentMethodSearch: @listAcct
  PaymentMethodSearchAdvanced: @listAcct
  PaymentMethodSearchBasic: @platformCommon
  PaymentMethodSearchRow: @listAcct
  PaymentMethodSearchRowBasic: @platformCommon
  PhoneCall: @actSched
  PhoneCallContact: @actSched
  PhoneCallContactList: @actSched
  PhoneCallSearch: @actSched
  PhoneCallSearchAdvanced: @actSched
  PhoneCallSearchBasic: @platformCommon
  PhoneCallSearchRow: @actSched
  PhoneCallSearchRowBasic: @platformCommon
  PhoneCallTimeItemList: @actSched
  PostingTransactionSummary: @platformCore
  PostingTransactionSummaryField: @platformCore
  PostingTransactionSummaryFilter: @platformCore
  PostingTransactionSummaryList: @platformCore
  Preferences: @platformMsgs
  PresentationItem: @platformCommon
  PresentationItemList: @listAcct
  Price: @listAcct
  PriceLevel: @listAcct
  PriceLevelSearch: @listAcct
  PriceLevelSearchAdvanced: @listAcct
  PriceLevelSearchBasic: @platformCommon
  PriceLevelSearchRow: @listAcct
  PriceLevelSearchRowBasic: @platformCommon
  PriceList: @listAcct
  Pricing: @listAcct
  PricingGroup: @listAcct
  PricingGroupSearch: @listAcct
  PricingGroupSearchAdvanced: @listAcct
  PricingGroupSearchBasic: @platformCommon
  PricingGroupSearchRow: @listAcct
  PricingGroupSearchRowBasic: @platformCommon
  PricingMatrix: @listAcct
  ProductFeedList: @listAcct
  ProjectTask: @actSched
  ProjectTaskAssignee: @actSched
  ProjectTaskAssigneeList: @actSched
  ProjectTaskAssignmentSearchBasic: @platformCommon
  ProjectTaskAssignmentSearchRowBasic: @platformCommon
  ProjectTaskPredecessor: @actSched
  ProjectTaskPredecessorList: @actSched
  ProjectTaskSearch: @actSched
  ProjectTaskSearchAdvanced: @actSched
  ProjectTaskSearchBasic: @platformCommon
  ProjectTaskSearchRow: @actSched
  ProjectTaskSearchRowBasic: @platformCommon
  ProjectTaskTimeItemList: @actSched
  PromotionCode: @listMkt
  PromotionCodeCurrency: @listMkt
  PromotionCodeCurrencyList: @listMkt
  PromotionCodeItems: @listMkt
  PromotionCodeItemsList: @listMkt
  PromotionCodePartners: @listMkt
  PromotionCodePartnersList: @listMkt
  PromotionCodeSearch: @listMkt
  PromotionCodeSearchAdvanced: @listMkt
  PromotionCodeSearchBasic: @platformCommon
  PromotionCodeSearchRow: @listMkt
  PromotionCodeSearchRowBasic: @platformCommon
  PurchLandedCostList: @tranPurch
  PurchaseOrder: @tranPurch
  PurchaseOrderExpense: @tranPurch
  PurchaseOrderExpenseList: @tranPurch
  PurchaseOrderItem: @tranPurch
  PurchaseOrderItemList: @tranPurch
  Rate: @listAcct
  RateList: @listAcct
  ReadResponse: @platformMsgs
  ReadResponseList: @platformMsgs
  Record: @platformCore
  RecordList: @platformCore
  RecordRef: @platformCore
  RecordRefList: @platformCore
  RecurrenceDowMaskList: @actSched
  ReturnAuthorization: @tranCust
  ReturnAuthorizationItem: @tranCust
  ReturnAuthorizationItemList: @tranCust
  ReturnAuthorizationPartnersList: @tranCust
  ReturnAuthorizationSalesTeam: @tranCust
  ReturnAuthorizationSalesTeamList: @tranCust
  RevRecSchedule: @listAcct
  RevRecScheduleRecurrence: @listAcct
  RevRecScheduleRecurrenceList: @listAcct
  RevRecScheduleSearch: @listAcct
  RevRecScheduleSearchAdvanced: @listAcct
  RevRecScheduleSearchBasic: @platformCommon
  RevRecScheduleSearchRow: @listAcct
  RevRecScheduleSearchRowBasic: @platformCommon
  RevRecTemplate: @listAcct
  RevRecTemplateRecurrence: @listAcct
  RevRecTemplateRecurrenceList: @listAcct
  RevRecTemplateSearch: @listAcct
  RevRecTemplateSearchAdvanced: @listAcct
  RevRecTemplateSearchBasic: @platformCommon
  RevRecTemplateSearchRow: @listAcct
  RevRecTemplateSearchRowBasic: @platformCommon
  SalesOrder: @tranSales
  SalesOrderItem: @tranSales
  SalesOrderItemList: @tranSales
  SalesOrderPartnersList: @tranSales
  SalesOrderSalesTeam: @tranSales
  SalesOrderSalesTeamList: @tranSales
  SalesOrderShipGroupList: @tranSales
  SalesRole: @listAcct
  SalesRoleSearch: @listAcct
  SalesRoleSearchAdvanced: @listAcct
  SalesRoleSearchBasic: @platformCommon
  SalesRoleSearchRow: @listAcct
  SalesRoleSearchRowBasic: @platformCommon
  SalesTaxItem: @listAcct
  SalesTeamList: @tranInvt
  SearchBooleanCustomField: @platformCore
  SearchBooleanField: @platformCore
  SearchColumnBooleanCustomField: @platformCore
  SearchColumnBooleanField: @platformCore
  SearchColumnCustomField: @platformCore
  SearchColumnCustomFieldList: @platformCore
  SearchColumnDateCustomField: @platformCore
  SearchColumnDateField: @platformCore
  SearchColumnDoubleCustomField: @platformCore
  SearchColumnDoubleField: @platformCore
  SearchColumnEnumMultiSelectCustomField: @platformCore
  SearchColumnEnumSelectField: @platformCore
  SearchColumnField: @platformCore
  SearchColumnLongCustomField: @platformCore
  SearchColumnLongField: @platformCore
  SearchColumnMultiSelectCustomField: @platformCore
  SearchColumnSelectCustomField: @platformCore
  SearchColumnSelectField: @platformCore
  SearchColumnStringCustomField: @platformCore
  SearchColumnStringField: @platformCore
  SearchColumnTextNumberField: @platformCore
  SearchCustomField: @platformCore
  SearchCustomFieldList: @platformCore
  SearchDateCustomField: @platformCore
  SearchDateField: @platformCore
  SearchDoubleCustomField: @platformCore
  SearchDoubleField: @platformCore
  SearchEnumMultiSelectCustomField: @platformCore
  SearchEnumMultiSelectField: @platformCore
  SearchLongCustomField: @platformCore
  SearchLongField: @platformCore
  SearchMoreRequest: @platformMsgs
  SearchMoreResponse: @platformMsgs
  SearchMoreWithIdRequest: @platformMsgs
  SearchMoreWithIdResponse: @platformMsgs
  SearchMultiSelectCustomField: @platformCore
  SearchMultiSelectField: @platformCore
  SearchNextRequest: @platformMsgs
  SearchNextResponse: @platformMsgs
  SearchPreferences: @platformMsgs
  SearchRecord: @platformCore
  SearchRequest: @platformMsgs
  SearchResponse: @platformMsgs
  SearchResult: @platformCore
  SearchRow: @platformCore
  SearchRowList: @platformCore
  SearchStringCustomField: @platformCore
  SearchStringField: @platformCore
  SearchTextNumberField: @platformCore
  SelectCustomFieldRef: @platformCore
  SerializedAssemblyItem: @listAcct
  SerializedInventoryItem: @listAcct
  SerializedInventoryItemLocations: @listAcct
  SerializedInventoryItemLocationsList: @listAcct
  SerializedInventoryItemNumbers: @listAcct
  SerializedInventoryItemNumbersList: @listAcct
  ServiceItemTaskTemplates: @listAcct
  ServiceItemTaskTemplatesList: @listAcct
  ServicePurchaseItem: @listAcct
  ServiceResaleItem: @listAcct
  ServiceSaleItem: @listAcct
  SessionResponse: @platformMsgs
  ShipAddress: @platformCommon
  SiteCategoryList: @listAcct
  SiteCategoryPresentationItemList: @listSite
  SiteCategorySearch: @listSite
  SiteCategorySearchAdvanced: @listSite
  SiteCategorySearchBasic: @platformCommon
  SiteCategorySearchRow: @listSite
  SiteCategorySearchRowBasic: @platformCommon
  SiteCategoryTranslation: @listSite
  SiteCategoryTranslationList: @listSite
  SoapFault: @platformFaults
  Solution: @listSupport
  SolutionSearch: @listSupport
  SolutionSearchAdvanced: @listSupport
  SolutionSearchBasic: @platformCommon
  SolutionSearchRow: @listSupport
  SolutionSearchRowBasic: @platformCommon
  SolutionTopics: @listSupport
  SolutionTopicsList: @listSupport
  Solutions: @listSupport
  SolutionsList: @listSupport
  SsoCredentials: @platformCore
  SsoLoginRequest: @platformMsgs
  SsoLoginResponse: @platformMsgs
  SsoPassport: @platformCore
  State: @listAcct
  Status: @platformCore
  StatusDetail: @platformCore
  StringCustomFieldRef: @platformCore
  Subscriptions: @listRel
  SubscriptionsList: @listRel
  Subsidiary: @listAcct
  SubsidiaryNexus: @listAcct
  SubsidiaryNexusList: @listAcct
  SubsidiarySearch: @listAcct
  SubsidiarySearchAdvanced: @listAcct
  SubsidiarySearchBasic: @platformCommon
  SubsidiarySearchRow: @listAcct
  SubsidiarySearchRowBasic: @platformCommon
  SubtotalItem: @listAcct
  SupportCase: @listSupport
  SupportCaseEscalateTo: @listSupport
  SupportCaseEscalateToList: @listSupport
  SupportCaseIssue: @listSupport
  SupportCaseOrigin: @listSupport
  SupportCasePriority: @listSupport
  SupportCaseSearch: @listSupport
  SupportCaseSearchAdvanced: @listSupport
  SupportCaseSearchBasic: @platformCommon
  SupportCaseSearchRow: @listSupport
  SupportCaseSearchRowBasic: @platformCommon
  SupportCaseSolutions: @listSupport
  SupportCaseSolutionsList: @listSupport
  SupportCaseStatus: @listSupport
  SupportCaseTimeItemList: @listSupport
  SupportCaseType: @listSupport
  Task: @actSched
  TaskContact: @actSched
  TaskContactList: @actSched
  TaskSearch: @actSched
  TaskSearchAdvanced: @actSched
  TaskSearchBasic: @platformCommon
  TaskSearchRow: @actSched
  TaskSearchRowBasic: @platformCommon
  TaskTimeItemList: @actSched
  TaxGroup: @listAcct
  TaxGroupTaxItem: @listAcct
  TaxGroupTaxItemList: @listAcct
  TaxType: @listAcct
  TaxTypeNexusesTax: @listAcct
  TaxTypeNexusesTaxList: @listAcct
  Term: @listAcct
  TermSearch: @listAcct
  TermSearchAdvanced: @listAcct
  TermSearchBasic: @platformCommon
  TermSearchRow: @listAcct
  TermSearchRowBasic: @platformCommon
  TimeBill: @tranEmp
  TimeBillSearch: @tranEmp
  TimeBillSearchAdvanced: @tranEmp
  TimeBillSearchBasic: @platformCommon
  TimeBillSearchRow: @tranEmp
  TimeBillSearchRowBasic: @platformCommon
  TimeItem: @platformCommon
  Topic: @listSupport
  TopicSearch: @listSupport
  TopicSearchAdvanced: @listSupport
  TopicSearchBasic: @platformCommon
  TopicSearchRow: @listSupport
  TopicSearchRowBasic: @platformCommon
  TopicSolution: @listSupport
  TopicSolutionList: @listSupport
  TransactionBodyCustomField: @setupCustom
  TransactionBodyCustomFieldFilter: @setupCustom
  TransactionBodyCustomFieldFilterList: @setupCustom
  TransactionColumnCustomField: @setupCustom
  TransactionColumnCustomFieldFilter: @setupCustom
  TransactionColumnCustomFieldFilterList: @setupCustom
  TransactionSearch: @tranSales
  TransactionSearchAdvanced: @tranSales
  TransactionSearchBasic: @platformCommon
  TransactionSearchRow: @tranSales
  TransactionSearchRowBasic: @platformCommon
  TransactionShipGroup: @tranSales
  TransferOrder: @tranInvt
  TransferOrderItem: @tranInvt
  TransferOrderItemList: @tranInvt
  Translation: @listAcct
  TranslationList: @listAcct
  UnexpectedErrorFault: @platformFaults
  UnitsType: @listAcct
  UnitsTypeSearch: @listAcct
  UnitsTypeSearchAdvanced: @listAcct
  UnitsTypeSearchBasic: @platformCommon
  UnitsTypeSearchRow: @listAcct
  UnitsTypeSearchRowBasic: @platformCommon
  UnitsTypeUom: @listAcct
  UnitsTypeUomList: @listAcct
  UpdateInviteeStatusListRequest: @platformMsgs
  UpdateInviteeStatusListResponse: @platformMsgs
  UpdateInviteeStatusReference: @platformCore
  UpdateInviteeStatusRequest: @platformMsgs
  UpdateInviteeStatusResponse: @platformMsgs
  UpdateListRequest: @platformMsgs
  UpdateListResponse: @platformMsgs
  UpdateRequest: @platformMsgs
  UpdateResponse: @platformMsgs
  UpsertListRequest: @platformMsgs
  UpsertListResponse: @platformMsgs
  UpsertRequest: @platformMsgs
  UpsertResponse: @platformMsgs
  Vendor: @listRel
  VendorAddressbook: @listRel
  VendorAddressbookList: @listRel
  VendorBill: @tranPurch
  VendorBillExpense: @tranPurch
  VendorBillExpenseList: @tranPurch
  VendorBillItem: @tranPurch
  VendorBillItemList: @tranPurch
  VendorCategory: @listAcct
  VendorCategorySearch: @listAcct
  VendorCategorySearchAdvanced: @listAcct
  VendorCategorySearchBasic: @platformCommon
  VendorCategorySearchRow: @listAcct
  VendorCategorySearchRowBasic: @platformCommon
  VendorCredit: @tranPurch
  VendorCreditApply: @tranPurch
  VendorCreditApplyList: @tranPurch
  VendorCreditExpense: @tranPurch
  VendorCreditExpenseList: @tranPurch
  VendorCreditItem: @tranPurch
  VendorCreditItemList: @tranPurch
  VendorPayment: @tranPurch
  VendorPaymentApply: @tranPurch
  VendorPaymentApplyList: @tranPurch
  VendorPaymentCredit: @tranPurch
  VendorPaymentCreditList: @tranPurch
  VendorPricingSchedule: @listRel
  VendorPricingScheduleList: @listRel
  VendorReturnAuthorization: @tranPurch
  VendorReturnAuthorizationExpense: @tranPurch
  VendorReturnAuthorizationExpenseList: @tranPurch
  VendorReturnAuthorizationItem: @tranPurch
  VendorReturnAuthorizationItemList: @tranPurch
  VendorRoles: @listRel
  VendorRolesList: @listRel
  VendorSearch: @listRel
  VendorSearchAdvanced: @listRel
  VendorSearchBasic: @platformCommon
  VendorSearchRow: @listRel
  VendorSearchRowBasic: @platformCommon
  WinLossReason: @listAcct
  WinLossReasonSearch: @listAcct
  WinLossReasonSearchAdvanced: @listAcct
  WinLossReasonSearchBasic: @platformCommon
  WinLossReasonSearchRow: @listAcct
  WinLossReasonSearchRowBasic: @platformCommon
  WorkOrder: @tranInvt
  WorkOrderItem: @tranInvt
  WorkOrderItemList: @tranInvt
  WriteResponse: @platformMsgs
  WriteResponseList: @platformMsgs
  WsRole: @platformCore
  WsRoleList: @platformCore
  getSelectValueRequest: @platformMsgs
  getSelectValueResponse: @platformMsgs
