// Generated by CoffeeScript 1.3.3
(function() {
  var NsUiClient, NsUiRecord, NsUiSession, QuickSummary, fs, media, qs, rpc, search, shipping,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    __slice = [].slice,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  rpc = require('./rpc');

  qs = require('querystring');

  fs = require('fs');

  shipping = require('./ui/shipping');

  search = require('./ui/search');

  media = require('./ui/media');

  NsUiClient = (function(_super) {

    __extends(NsUiClient, _super);

    function NsUiClient(options) {
      if (options == null) {
        options = {};
      }
      NsUiClient.__super__.constructor.apply(this, arguments);
      this.session = {};
    }

    NsUiClient.prototype.nlqsr = function(type, path, options, cb) {
      var nlq, _ref;
      if (type == null) {
        type = 'xml';
      }
      if (path == null) {
        path = '/';
      }
      if (options == null) {
        options = {};
      }
      nlq = (_ref = options.nlquery) != null ? _ref : {};
      switch (type) {
        case 'xml':
          nlq.xml = 'T';
          break;
        case 'script':
          nlq.s = 'T';
      }
      return this.get("" + path + "__" + (qs.stringify(nlq)) + ".nlqs", options, cb);
    };

    NsUiClient.prototype.nlapir = function(attr, elements, options, cb) {
      var nr, _ref, _ref1;
      if ((_ref = elements['@']) == null) {
        elements['@'] = attr;
      }
      nr = {
        nlapiRequest: elements
      };
      return this.xmlr((_ref1 = options.path) != null ? _ref1 : void 0, nr, function(res) {
        if (res.statusCode === 200) {
          return res.parseBody('xml', function(parsed) {
            return cb(parsed, res);
          });
        } else {
          return cb(null, res);
        }
      });
    };

    NsUiClient.prototype.login = function(user, password, cb) {
      var params, _ref,
        _this = this;
      if (typeof user === 'object') {
        params = user;
      } else {
        params = {
          email: user
        };
      }
      if ((_ref = params.password) == null) {
        params.password = password;
      }
      return this.formr('/app/login/nllogin.nl', params, function(res) {
        res.success = !res.error && res.statusCode === 302;
        _this.session = new NsUiSession(user, res.cookies);
        return cb(res, _this.session);
      });
    };

    NsUiClient.prototype.loginAs = function(email, password, company, role, cb) {
      var user;
      user = {
        email: email,
        company: company,
        role: role
      };
      return this.login(user, password, cb);
    };

    NsUiClient.prototype.wslogin = function(email, password, company, role, taskid, recordId, edit, cb) {
      var params;
      if (recordId == null) {
        recordId = -1;
      }
      if (edit == null) {
        edit = 'F';
      }
      params = {
        email: email,
        password: password,
        c: company,
        role: role,
        taskid: taskid,
        id: recordId,
        e: edit
      };
      return this.formr('/app/webservices/wslogin.nl', params, function(res) {
        res.success = !res.error && res.statusCode === 302;
        this.session = new NsUiSession(user, res.cookies);
        return cb(res, this.session);
      });
    };

    NsUiClient.prototype.logout = function() {
      var cb, noback, uri, _i;
      noback = 2 <= arguments.length ? __slice.call(arguments, 0, _i = arguments.length - 1) : (_i = 0, []), cb = arguments[_i++];
      if (noback) {
        uri = '/pages/nllogoutnoback.jsp';
      } else {
        uri = '/pages/nllogout.jsp';
      }
      return this.get('/pages/nllogoutnoback.jsp', {}, cb);
    };

    NsUiClient.prototype.switchRoles = function(nkey, hash, cb) {
      return this.get('/app/login/dashboard.nl', {
        query: {
          id: nkey,
          h: hash
        }
      }, function(res) {
        var _ref;
        res.success = !res.error && res.statusCode === 302;
        if (res.success && (this.session != null)) {
          this.session.loadCookies(res.cookies);
        } else {
          if ((_ref = this.session) == null) {
            this.session = new NsUiSession({
              nkey: nkey
            }, res.cookies);
          }
        }
        return cb(res, this.session);
      });
    };

    NsUiClient.prototype.checkForAccess = function(company, email, cb) {
      return this.get('/app/common/entity/checkemailaccess.nl', {
        query: {
          compid: company,
          email: email
        }
      }, function(res) {
        if (/parent.warnemailaccess=false;/.test(res.body)) {
          return cb(false, res);
        } else if (/parent.warnemailaccess=true;/.test(res.body)) {
          return cb(true, res);
        } else {
          return cb(void 0, res);
        }
      });
    };

    NsUiClient.prototype.getContext = function(cb) {
      var _this = this;
      return this.jsonr('getContext', [], {}, function(res) {
        var _ref;
        if (!res.error) {
          _this.session.context = (_ref = res.result) != null ? _ref : {};
        }
        return cb(res, _this.session.context);
      });
    };

    NsUiClient.prototype.getColorPreferences = function(cb) {
      var _this = this;
      return this.jsonr('getColorPreferences', [], {}, function(res) {
        var _ref;
        if (!res.error) {
          _this.session.colors = (_ref = res.result) != null ? _ref : {};
        }
        return cb(res, _this.session.colors);
      });
    };

    NsUiClient.prototype.getAllSessionObjects = function(cb) {
      return this.jsonr('getAllSessionObjects', [], {}, cb);
    };

    NsUiClient.prototype.getSessionObject = function(name, cb) {
      return this.jsonr('getSessionObject', [name], {}, cb);
    };

    NsUiClient.prototype.getScriptPreferences = function(recordType, cb) {
      return this.jsonr('getScriptPrefs', [recordType], {}, cb);
    };

    NsUiClient.prototype.getPreference = function(name, cb) {
      var _this = this;
      return this.jsonr('getPref', [name], {}, function(res) {
        var _ref;
        if (!res.error && (res.result != null) !== null) {
          _this.session.preferences[name] = res.result;
        }
        return cb(res, (_ref = _this.session.preferences[name]) != null ? _ref : null);
      });
    };

    NsUiClient.prototype.getPermission = function(name, cb) {
      return this.jsonr('getPerm', [name], {}, cb);
    };

    NsUiClient.prototype.getFeature = function(name, cb) {
      return this.jsonr('getFeature', [name], {}, cb);
    };

    NsUiClient.prototype.getTaskLinks = function(cb) {
      var _this = this;
      return this.jsonr('getTaskLinks', [], {}, function(res) {
        var _ref;
        if (!res.error) {
          _this.session.taskLinks = (_ref = res.result) != null ? _ref : {};
        }
        return cb(res, _this.session.taskLinks);
      });
    };

    NsUiClient.prototype.getRecordTypes = function(cb) {
      var _this = this;
      return this.jsonr('getRecordTypes', [], {}, function(res) {
        var _ref;
        if (!res.error) {
          _this.session.recordTypes = (_ref = res.result) != null ? _ref : {};
        }
        return cb(res, _this.session.recordTypes);
      });
    };

    NsUiClient.prototype.getUsageUnits = function(cb) {
      var _this = this;
      return this.jsonr('getUsageUnits', [], {}, function(res) {
        var _ref;
        if (!res.error) {
          _this.session.usageUnits = (_ref = res.result) != null ? _ref : {};
        }
        return cb(res, _this.session.usageUnits);
      });
    };

    NsUiClient.prototype.getTotalScriptGovernance = function(bundle, cb) {
      if (bundle == null) {
        bundle = -1;
      }
      return this.jsonr('getTotalScriptGovernance', [bundle], {}, cb);
    };

    NsUiClient.prototype.encrypt = function(str, type, key, cb) {
      if (type == null) {
        type = 'sha1';
      }
      if (key == null) {
        key = null;
      }
      return this.jsonr('encrypt', [str, type, key], {}, cb);
    };

    NsUiClient.prototype.decrypt = function(str, type, key, cb) {
      if (type == null) {
        type = 'sha1';
      }
      if (key == null) {
        key = null;
      }
      return this.jsonr('decrypt', [str, type, key], {}, cb);
    };

    NsUiClient.prototype.deleteRecord = function(type, id, cb) {
      return this.jsonr('deleteRecord', [type, id], {}, cb);
    };

    NsUiClient.prototype.exchangeRate = function(fromCurrency, toCurrency, effectDate, cb) {
      var dateStr;
      if (effectDate == null) {
        effectDate = new Date();
      }
      dateStr = "" + (effectDate.getMonth() + 1) + "/" + (effectDate.getDate()) + "/" + (effectDate.getFullYear());
      return this.jsonr('exchangeRate', [fromCurrency, toCurrency, dateStr], {}, cb);
    };

    NsUiClient.prototype.resolveURL = function(type, identifier, id, pagemode, cb) {
      switch (type.toLowerCase()) {
        case 'suitelet':
          if (pagemode === true) {
            pagemode = 'external';
          } else if (pagemode === false) {
            pagemode = 'internal';
          }
          break;
        case 'record':
          if (pagemode === true) {
            pagemode = 'edit';
          } else if (pagemode === false) {
            pagemode = 'view';
          }
      }
      return this.jsonr('resolveURL', [type, identifier != null ? identifier : null, id != null ? id : null, pagemode != null ? pagemode : null], {}, cb);
    };

    NsUiClient.prototype.attachRecord = function(srcType, srcId, destType, destId, options, cb) {
      return this.jsonr('attachRecord', [srcType, srcId, destType, destId, options != null ? options : {}], {}, cb);
    };

    NsUiClient.prototype.detachRecord = function(type, id, parentType, parentId, options, cb) {
      return this.jsonr('detachRecord', [srcType, srcId, parentType, parentId, options != null ? options : {}], {}, cb);
    };

    NsUiClient.prototype.logExecution = function(scriptId, recordType, type, title, details, cb) {
      return this.jsonr('logExecution', [scriptId, recordType, type, title, details != null ? details : null], {}, cb);
    };

    NsUiClient.prototype.logError = function(code, msg, id, fn, scriptId, notify, recordType, recordId, cb) {
      return this.jsonr('logError', [code, msg, id, fn, scriptId, !notify, suppressNotification, recordType, recordId], {}, cb);
    };

    NsUiClient.prototype._nlapiRecReq = function(attr, params, cb) {
      var el,
        _this = this;
      if (params) {
        el = {
          loadParams: params
        };
      } else {
        el = {};
      }
      return this.nlapir(attr, el, {}, function(parsed, res) {
        if (parsed) {
          return cb(new NsUiRecord().extract(res.parsed), res);
        } else {
          return cb(parsed, res);
        }
      });
    };

    NsUiClient.prototype.createRecord = function(recordType, initializeDefaults, cb) {
      var attr;
      attr = {
        type: 'nlapiCreateRecord',
        recordType: recordType
      };
      return this._nlapiRecReq(attr, initializeDefaults, function(rec, res) {
        if (rec) {
          rec.logOperation('createRecord', {
            initializeDefaults: initializeDefaults
          });
        }
        return cb(rec, res);
      });
    };

    NsUiClient.prototype.loadRecord = function(recordType, id, initializeDefaults, cb) {
      var attr;
      attr = {
        type: 'nlapiLoadRecord',
        recordType: recordType,
        id: id
      };
      return this._nlapiRecReq(attr, initializeDefaults, function(rec, res) {
        if (rec) {
          rec.logOperation('loadRecord', {
            id: id,
            initializeDefaults: initializeDefaults
          });
        }
        return cb(rec, res);
      });
    };

    NsUiClient.prototype.copyRecord = function(recordType, id, initializeDefaults, cb) {
      var attr;
      attr = {
        type: 'nlapiCopyRecord',
        recordType: recordType,
        id: id
      };
      return this._nlapiRecReq(attr, initializeDefaults, function(rec, res) {
        if (rec) {
          rec.logOperation('copyRecord', {
            id: id,
            initializeDefaults: initializeDefaults
          });
        }
        return cb(rec, res);
      });
    };

    NsUiClient.prototype.transformRecord = function(recordType, id, transformType, transformDefaults, cb) {
      var attr;
      attr = {
        type: 'nlapiTransformRecord',
        recordType: recordType,
        id: id,
        transformType: transformType
      };
      return this._nlapiRecReq(attr, transformDefaults, function(rec, res) {
        if (rec) {
          rec.logOperation('transformRecord', {
            type: recordType,
            id: id,
            transformType: transformType,
            transformDefaults: transformDefaults
          });
        }
        return cb(rec, res);
      });
    };

    NsUiClient.prototype.submitRecord = function(record, options, cb) {
      var attr, el, _ref, _ref1, _ref2;
      attr = {
        type: 'nlapiSubmitRecord',
        enableSourcing: (_ref = options.enableSourcing) != null ? _ref : true,
        disableTriggers: (_ref1 = options.disableTriggers) != null ? _ref1 : false,
        ignoreMandatoryFields: (_ref2 = options.ignoreMandatoryFields) != null ? _ref2 : true
      };
      if (typeof record.serialize === 'function') {
        el = record.serialize();
      } else {
        el = {
          record: record
        };
      }
      return this.nlapir(attr, el, {}, cb);
    };

    NsUiClient.prototype.submitField = function(recordType, id, fields, options, cb) {
      var attr, el, k, v, _ref, _ref1;
      attr = {
        type: 'nlapiSubmitField',
        recordType: recordType,
        id: id,
        enableSourcing: (_ref = options.enableSourcing) != null ? _ref : false,
        disableTriggers: (_ref1 = options.disableTriggers) != null ? _ref1 : false
      };
      el = (function() {
        var _results;
        _results = [];
        for (k in fields) {
          v = fields[k];
          _results.push({
            field: {
              name: k,
              value: v
            }
          });
        }
        return _results;
      })();
      return this.nlapir(attr, el, {}, cb);
    };

    NsUiClient.prototype.sendEmail = function(author, recipient, subject, body, cc, bcc, records, cb) {
      var attr, el, k, rf, _i, _len;
      rf = ['transaction', 'entity', 'recordType', 'record', 'activity'];
      attr = {
        type: 'nlapiSendEmail'
      };
      el = {
        author: author,
        recipient: recipient,
        subject: subject,
        body: body,
        cc: cc,
        bcc: bcc
      };
      if (records) {
        for (_i = 0, _len = rf.length; _i < _len; _i++) {
          k = rf[_i];
          el[rf[k]] = records[rf[k]];
        }
      }
      return this.nlapir(attr, el, {}, cb);
    };

    NsUiClient.prototype.sendFax = function(author, recipient, subject, body, records, cb) {
      var attr, el, k, rf, _i, _len;
      rf = ['transaction', 'entity', 'recordType', 'record', 'activity'];
      attr = {
        type: 'nlapiSendFax'
      };
      el = {
        author: author,
        recipient: recipient,
        subject: subject,
        body: body
      };
      if (records) {
        for (_i = 0, _len = rf.length; _i < _len; _i++) {
          k = rf[_i];
          el[rf[k]] = records[rf[k]];
        }
      }
      return this.nlapir(attr, el, {}, cb);
    };

    NsUiClient.prototype.requestURL = function(method, url, query, body, headers, cb) {
      var attr, el, name, value, _ref, _ref1;
      if (method == null) {
        method = 'POST';
      }
      attr = {
        type: 'nlapiRequestURL'
      };
      el = {
        url: url,
        method: method,
        body: body
      };
      for (name in query) {
        value = query[name];
        if ((_ref = el.param) == null) {
          el.param = [];
        }
        el.param.push({
          name: name,
          value: value
        });
      }
      for (name in headers) {
        value = headers[name];
        if ((_ref1 = el.header) == null) {
          el.header = [];
        }
        el.header.push({
          name: name,
          value: value
        });
      }
      return this.nlapir(attr, el, {}, cb);
    };

    NsUiClient.prototype.fetchMyRoles = function(cb) {
      return this.get(this.session.addSticky('ROLEMENU', '/core/elements/compound/NLRoleMenu.nl'), {}, function(res) {
        var m, match, matches, roles;
        matches = res.body.match(/m_cRR_d1\[\d+\] = new Array\('.+\);/g);
        roles = (function() {
          var _i, _len, _results;
          _results = [];
          for (_i = 0, _len = matches.length; _i < _len; _i++) {
            match = matches[_i];
            m = /'([\w\s]+)\',\'(\/app\/login\/dashboard.nl\?id=(\d+)&h=(\w+))/.exec(match);
            _results.push({
              title: m[1],
              url: m[2],
              nkey: m[3],
              hash: m[4]
            });
          }
          return _results;
        })();
        return cb(roles, res);
      });
    };

    NsUiClient.prototype.getHoverData = function(recordType, id, options, cb) {
      var key, query, value;
      recordType = recordType.toUpperCase();
      query = {
        rectype: recordType,
        recordType: recordType,
        id: id,
        templateType: 'DEFAULT_TEMPLATE',
        quicksummary: 'T',
        check: 'F'
      };
      for (key in options) {
        value = options[key];
        query[key] = value;
      }
      return this.get('/app/elements/tooltip/NLTooltipRequestHandler.nl', {
        query: query
      }, function(res) {
        if (res.statusCode === 200) {
          return res.parseBody('json', function(parsed) {
            return cb(new QuickSummary(parsed), res);
          });
        } else {
          return cb(res.parsed, res);
        }
      });
    };

    NsUiClient.prototype.checkForHover = function(recordType, id, cb) {
      return this.getHoverData(recordType, id, {
        check: 'T'
      }, function(parsed, res) {
        return cb(parsed.success, res);
      });
    };

    NsUiClient.prototype["export"] = function(path, options, cb) {
      var query, _ref, _ref1, _ref2, _ref3, _ref4, _ref5;
      if (options == null) {
        options = {};
      }
      query = {
        sortcol: (_ref = options.sortcol) != null ? _ref : '',
        sortdir: (_ref1 = options.sortdir) != null ? _ref1 : 'ASC',
        csv: (_ref2 = options.csv) != null ? _ref2 : 'HTML',
        OfficeXML: (_ref3 = options.OfficeXML) != null ? _ref3 : 'F',
        pdf: (_ref4 = options.pdf) != null ? _ref4 : '',
        showall: (_ref5 = options.showall) != null ? _ref5 : 'F'
      };
      return this.get(path, {
        query: query
      }, cb);
    };

    NsUiClient.prototype.exportPDF = function(path, options, cb) {
      if (options == null) {
        options = {};
      }
      options.pdf = 'T';
      return this["export"](path, options, cb);
    };

    NsUiClient.prototype.exportCSV = function(path, options, cb) {
      if (options == null) {
        options = {};
      }
      path = path.replace(/\.nl(\?[^/]+)?$/, '.csv');
      options.csv = 'Export';
      return this["export"](path, options, function(res) {
        if (res.statusCode === 200) {
          return res.parseBody('csv', function(parsed) {
            return cb(parsed, res);
          });
        } else {
          return cb(null, res);
        }
      });
    };

    NsUiClient.prototype.exportXLS = function(path, options, cb) {
      if (options == null) {
        options = {};
      }
      path = path.replace(/\.nl(\?[^/]+)?$/, '.xls');
      options.OfficeXML = 'T';
      options.csv = 'Export';
      return this["export"](path, options, cb);
    };

    NsUiClient.prototype.previewTemplate = function(id, entity, cb) {
      var query;
      query = {
        id: id
      };
      if (entity) {
        query.entity = entity;
      }
      return this.get('/app/crm/common/merge/previewtemplate.nl', {
        query: query
      }, cb);
    };

    NsUiClient.prototype.respondToEvent = function(accepted, eventId, cb) {
      var response;
      if (accepted == null) {
        accepted = true;
      }
      if (accepted) {
        response = 'accepted';
      } else {
        response = 'declined';
      }
      return this.get('/app/crm/calendar/eventresponse.nl', {
        query: {
          l: 'T',
          istimed: 'T',
          eventId: eventId,
          response: response
        }
      }, cb);
    };

    NsUiClient.prototype.listRecentRecords = function(cb) {};

    NsUiClient.prototype.downloadRecentRecordCSV = function(options, cb) {
      if (options == null) {
        options = {};
      }
      return this.exportCSV('/app/common/otherlists/recentrecords.nl', options, cb);
    };

    NsUiClient.prototype.addShortcut = function(label, taskid, params, cb) {
      if (params == null) {
        params = {};
      }
      params = qs.stringify(params);
      return this.get('/core/pages/addShortcut.nl', {
        query: {
          xml: 'T',
          label: label,
          taskid: taskid,
          params: params
        }
      }, cb);
    };

    return NsUiClient;

  })(rpc.Client);

  NsUiSession = (function() {

    function NsUiSession(user, cookies) {
      this.creds = user != null ? user : {
        email: null,
        password: null,
        company: null,
        role: null,
        nskey: null
      };
      this.auth = {
        JSESSIONID: null,
        lastUser: null,
        NS_VER: null
      };
      this.stickyTags = {};
      this.context = {};
      this.recordTypes = {};
      this.taskLinks = {};
      this.usageUnits = {};
      this.objects = {};
      this.preferences = {};
      this.features = {};
      this.colors = {};
      this.loadCookies(cookies);
    }

    NsUiSession.prototype.loadCookies = function(cookies) {
      var name, parts, tag, udata, value, vdata, _ref, _results;
      _results = [];
      for (name in cookies) {
        value = cookies[name];
        switch (name) {
          case 'JSESSIONID':
            _results.push(this.auth.JSESSIONID = this.id = value);
            break;
          case 'lastUser':
            this.auth.lastUser = value;
            udata = value.split('_');
            _results.push(this.lastUser = {
              account: udata[0],
              entity: udata[1],
              role: udata[2],
              input: value
            });
            break;
          case 'NS_VER':
            this.auth.NS_VER = value;
            vdata = value.split('.');
            _results.push(this.nsVersion = {
              year: vdata[0],
              major: vdata[1],
              minor: vdata[2],
              revision: (_ref = vdata[3]) != null ? _ref : null
            });
            break;
          case 'stickytags':
            _results.push((function() {
              var _i, _len, _ref1, _results1;
              _ref1 = value.split(',');
              _results1 = [];
              for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
                tag = _ref1[_i];
                parts = tag.split(':');
                _results1.push(this.stickyTags[parts[0]] = parts[1]);
              }
              return _results1;
            }).call(this));
            break;
          default:
            _results.push(void 0);
        }
      }
      return _results;
    };

    NsUiSession.prototype.addSticky = function(taskId, pathOrObj) {
      var _ref, _ref1, _ref2;
      if (typeof pathOrObj === 'string') {
        if (/\?./.test(pathOrObj)) {
          return "" + pathOrObj + "&t=" + ((_ref = this.stickyTags[taskId]) != null ? _ref : '');
        } else {
          return "" + pathOrObj + "?t=" + ((_ref1 = this.stickyTags[taskId]) != null ? _ref1 : '');
        }
      } else if (typeof pathOrObj === 'object') {
        return pathOrObj.t = (_ref2 = this.stickyTags[taskId]) != null ? _ref2 : '';
      } else {
        return this.stickyTags[taskId];
      }
    };

    return NsUiSession;

  })();

  NsUiRecord = (function() {

    function NsUiRecord(recordType, id) {
      this.recordType = recordType != null ? recordType : null;
      this.id = id != null ? id : null;
      this.serialize = __bind(this.serialize, this);

      this.fields = {};
      this.fieldNames = [];
      this.lineTypes = {};
      this.lineFields = {};
      this.lineItems = {};
      this.currentLineItems = {};
      this.currentLineItemIndexes = {};
      this.matrixFields = {};
      this.initialized = false;
      this.operations = [];
    }

    NsUiRecord.prototype.extract = function(res) {
      var key, mach, matts, rec, value, _i, _len, _ref, _ref1, _ref2, _ref3, _ref4, _ref5, _ref6, _ref7, _ref8;
      rec = (_ref = (_ref1 = res.nlapiResponse) != null ? _ref1.record : void 0) != null ? _ref : null;
      for (key in rec) {
        value = rec[key];
        switch (key) {
          case '@':
            this.id = (_ref2 = value.id) != null ? _ref2 : null;
            this.recordType = (_ref3 = value.recordType) != null ? _ref3 : null;
            this.fieldNames = (_ref4 = value.fields.split(',')) != null ? _ref4 : [];
            this.permLevel = (_ref5 = value.perm) != null ? _ref5 : -1;
            break;
          case 'machine':
            for (_i = 0, _len = value.length; _i < _len; _i++) {
              mach = value[_i];
              matts = (_ref6 = mach['@']) != null ? _ref6 : {};
              if (Array.isArray(mach.line)) {
                this.lineItems[matts.name] = mach.line;
              } else if (mach.line != null) {
                this.lineItems[matts.name] = [mach.line];
              }
              this.lineTypes[matts.name] = (_ref7 = matts.type) != null ? _ref7 : null;
              this.lineFields[matts.name] = (_ref8 = matts.fields) != null ? _ref8.split(',') : void 0;
              if (matts.matrixfields != null) {
                this.matrixFields[matts.name] = matts.matrixfields.split(',');
              }
            }
            break;
          default:
            this.setFld(key, value);
        }
      }
      this.initialized = true;
      return this;
    };

    NsUiRecord.prototype.serialize = function() {
      var el, op, ops, type, _i, _len, _ref, _ref1;
      ops = [];
      type = 'load';
      _ref = this.operations;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        op = _ref[_i];
        el = op.args;
        el['@'] = {
          type: type,
          name: op.operation
        };
        ops.push({
          operation: el
        });
        type = 'data';
      }
      return {
        record: {
          '@': {
            recordType: this.recordType,
            id: (_ref1 = this.id) != null ? _ref1 : null
          },
          operations: ops
        }
      };
    };

    NsUiRecord.prototype.logOperation = function(operation, args) {
      if (this.initialized) {
        return this.operations.push({
          operation: operation,
          args: args
        });
      }
    };

    NsUiRecord.prototype.setFieldValue = function(name, value) {
      this.fields[name] = value;
      return this.logOperation('setFieldValue', {
        field: name,
        value: value
      });
    };

    NsUiRecord.prototype.setFieldValues = function(name, values) {
      if (!Array.isArray(values)) {
        values = [values];
      }
      this.fields[name] = values;
      return this.logOperation('setFieldValues', {
        field: name,
        value: values
      });
    };

    NsUiRecord.prototype.setFld = function() {
      var name, value, values, _ref;
      name = arguments[0], values = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
      if (arguments.length > 2) {
        this.setFieldValues(name, values);
      } else {
        value = (_ref = values[0]) != null ? _ref : null;
        if (Array.isArray(value)) {
          this.setFieldValues(name, value);
        } else {
          this.setFieldValue(name, value);
        }
      }
      return this;
    };

    NsUiRecord.prototype.insertLineItem = function(type, line) {
      var _base, _ref;
      if ((_ref = (_base = this.lineItems)[type]) == null) {
        _base[type] = [];
      }
      this.lineItems.splice(line, 0, []);
      return this.logOperation('insertLineItem', {
        type: type
      });
    };

    NsUiRecord.prototype.removeLineItem = function(type, line) {
      var _ref;
      if ((_ref = this.lineItems[type]) != null) {
        _ref.splice(line, 1);
      }
      return this.logOperation('removeLineItem', {
        type: type
      });
    };

    NsUiRecord.prototype.selectLineItem = function(type, linenum) {
      var key, value, _ref;
      this.currentLineItems[type] = {};
      this.currentLineItemIndexes[type] = linenum;
      _ref = this.lineItems[type];
      for (key in _ref) {
        value = _ref[key];
        this.currentLineItems[type][key] = value;
      }
      return this.logOperation('selectLineNum', {
        type: type,
        linenum: linenum
      });
    };

    NsUiRecord.prototype.selectNewLineItem = function(type) {
      if (this.lineTypes[type] !== 'edit') {
        throw 'Invalid sublist operation';
      }
      this.currentLineItems[type] = {};
      this.currentLineIndexes[type] = this.lineItems[type].length + 1;
      return this.logOperation('selectNewLineItem', {
        type: type
      });
    };

    NsUiRecord.prototype.commitLineItem = function(type) {
      var key, line, value, _ref;
      line = this.currentLineItemIndexes[type];
      _ref = this.currentLineItems[type];
      for (key in _ref) {
        value = _ref[key];
        this.lineItems[type][line][key] = value;
      }
      return this.logOperation('commitLineItem', {
        type: type
      });
    };

    NsUiRecord.prototype.cancelLineItem = function(type) {
      this.currentLineItems[type] = null;
      this.currentLineItemIndexes[type] = null;
      return this.logOperation('cancelLineItem', {
        type: type
      });
    };

    NsUiRecord.prototype.setMatrixValue = function(type, field, column, value) {
      var fh, _ref;
      fh = (_ref = this.fields["" + type + "header"]) != null ? _ref : null;
      this.fields["" + fh + column] = value;
      return this.logOperation('setMatrixValue', {
        type: type,
        field: field,
        column: column,
        value: value
      });
    };

    NsUiRecord.prototype.isMatrixField = function(type, field) {
      var _ref;
      return __indexOf.call((_ref = this.fields["" + type + "matrixfields"]) != null ? _ref.split(',') : void 0, field) >= 0;
    };

    NsUiRecord.prototype.getMatrixValue = function(type, field, column) {
      var _ref;
      return (_ref = this.fields[this.fields["" + type + "header"] + column]) != null ? _ref : void 0;
    };

    return NsUiRecord;

  })();

  QuickSummary = (function() {

    function QuickSummary(response) {
      var freg, key, value, _base, _name, _ref;
      this.fields = {};
      for (key in response) {
        value = response[key];
        freg = /([A-Za-z]+)(\d+)/gm.exec(key);
        if (freg) {
          if ((_ref = (_base = this.fields)[_name = freg[2]]) == null) {
            _base[_name] = {};
          }
          switch (freg != null ? freg[1] : void 0) {
            case 'fieldName':
              this.fields[freg[2]].name = value;
              break;
            case 'display':
              this.fields[freg[2]].display = value;
              break;
            case 'fieldValue':
              if (value === '&nbsp;') {
                value = '';
              }
              this.fields[freg[2]].value = value;
          }
        } else {
          this[key] = value;
        }
      }
    }

    QuickSummary.prototype.getVisibleFields = function() {
      var fld, i, _ref, _results;
      _ref = this.fields;
      _results = [];
      for (i in _ref) {
        fld = _ref[i];
        if (fld.display === 'visible') {
          _results.push(fld);
        }
      }
      return _results;
    };

    return QuickSummary;

  })();

  module.exports = {
    shipping: shipping.extend(NsUiClient),
    search: search.extend(NsUiClient),
    media: media.extend(NsUiClient),
    Client: NsUiClient,
    Session: NsUiSession,
    Record: NsUiRecord
  };

}).call(this);
