// Generated by CoffeeScript 1.3.3
(function() {
  var enums, schemas;

  enums = {
    actSchedTyp: require('./actSchedTyp'),
    demandPlanningTyp: require('./demandPlanningTyp'),
    docFileCabTyp: require('./docFileCabTyp'),
    generalCommTyp: require('./generalCommTyp'),
    tranCustTyp: require('./tranCustTyp'),
    tranEmpTyp: require('./tranEmpTyp'),
    tranInvtTyp: require('./tranInvtTyp'),
    tranFinTyp: require('./tranFinTyp'),
    tranPurchTyp: require('./tranPurchTyp'),
    listRelTyp: require('./listRelTyp'),
    tranSalesTyp: require('./tranSalesTyp'),
    listSupportTyp: require('./listSupportTyp'),
    platformFaultTyp: require('./platformFaultTyp'),
    platformCoreTyp: require('./platformCoreTyp'),
    setupCustomTyp: require('./setupCustomTyp'),
    platformCommonTyp: require('./platformCommonTyp'),
    listEmpTyp: require('./listEmpTyp'),
    listAcctTyp: require('./listAcctTyp'),
    listMktTyp: require('./listMktTyp')
  };

  schemas = {
    platformFaults: require('./platformFaults'),
    platformCore: require('./platformCore'),
    platformMsgs: require('./platformMsgs'),
    actSched: require('./actSched'),
    generalComm: require('./generalComm'),
    listRel: require('./listRel'),
    tranPurch: require('./tranPurch'),
    listSupport: require('./listSupport'),
    tranSales: require('./tranSales'),
    listAcct: require('./listAcct'),
    tranFin: require('./tranFin'),
    tranCust: require('./tranCust'),
    tranBank: require('./tranBank'),
    platformCommon: require('./platformCommon'),
    tranGeneral: require('./tranGeneral'),
    listEmp: require('./listEmp'),
    setupCustom: require('./setupCustom'),
    docFileCab: require('./docFileCab'),
    tranInvt: require('./tranInvt'),
    listSite: require('./listSite'),
    tranEmp: require('./tranEmp'),
    listMkt: require('./listMkt'),
    demandPlanning: require('./demandPlanning')
  };

  module.exports = {
    enums: enums,
    schemas: schemas
  };

}).call(this);
