// Generated by CoffeeScript 1.3.3
(function() {
  var simpleTypes;

  simpleTypes = module.exports = {
    ReturnAuthorizationOrderStatus: {
      base: 'xsd:string',
      values: ["_pendingApproval", "_pendingReceipt"]
    }
  };

}).call(this);
