// Generated by CoffeeScript 1.3.3
(function() {

  exports.complexTypes = {
    Budget: {
      base: 'platformCore:Record',
      attributes: {
        internalId: {
          type: 'xsd:string'
        }
      },
      elements: {
        year: {
          type: 'platformCore:RecordRef',
          minOccurs: '0'
        },
        customer: {
          type: 'platformCore:RecordRef',
          minOccurs: '0'
        },
        item: {
          type: 'platformCore:RecordRef',
          minOccurs: '0'
        },
        "class": {
          type: 'platformCore:RecordRef',
          minOccurs: '0'
        },
        department: {
          type: 'platformCore:RecordRef',
          minOccurs: '0'
        },
        location: {
          type: 'platformCore:RecordRef',
          minOccurs: '0'
        },
        account: {
          type: 'platformCore:RecordRef',
          minOccurs: '0'
        },
        subsidiary: {
          type: 'platformCore:RecordRef',
          minOccurs: '0'
        },
        category: {
          type: 'platformCore:RecordRef',
          minOccurs: '0'
        },
        budgetType: {
          type: 'tranFinTyp:BudgetBudgetType',
          minOccurs: '0'
        },
        currency: {
          type: 'platformCore:RecordRef',
          minOccurs: '0'
        },
        periodAmount1: {
          type: 'xsd:double',
          minOccurs: '0'
        },
        periodAmount2: {
          type: 'xsd:double',
          minOccurs: '0'
        },
        periodAmount3: {
          type: 'xsd:double',
          minOccurs: '0'
        },
        periodAmount4: {
          type: 'xsd:double',
          minOccurs: '0'
        },
        periodAmount5: {
          type: 'xsd:double',
          minOccurs: '0'
        },
        periodAmount6: {
          type: 'xsd:double',
          minOccurs: '0'
        },
        periodAmount7: {
          type: 'xsd:double',
          minOccurs: '0'
        },
        periodAmount8: {
          type: 'xsd:double',
          minOccurs: '0'
        },
        periodAmount9: {
          type: 'xsd:double',
          minOccurs: '0'
        },
        periodAmount10: {
          type: 'xsd:double',
          minOccurs: '0'
        },
        periodAmount11: {
          type: 'xsd:double',
          minOccurs: '0'
        },
        periodAmount12: {
          type: 'xsd:double',
          minOccurs: '0'
        },
        amount: {
          type: 'xsd:double',
          minOccurs: '0'
        }
      }
    },
    BudgetSearch: {
      base: 'platformCore:SearchRecord',
      elements: {
        basic: {
          type: 'platformCommon:BudgetSearchBasic',
          minOccurs: '0'
        }
      }
    },
    BudgetSearchAdvanced: {
      base: 'platformCore:SearchRecord',
      attributes: {
        savedSearchId: {
          type: 'xsd:string'
        },
        savedSearchScriptId: {
          type: 'xsd:string'
        }
      },
      elements: {
        criteria: {
          type: 'tranFin:BudgetSearch',
          minOccurs: '0'
        },
        columns: {
          type: 'tranFin:BudgetSearchRow',
          minOccurs: '0'
        }
      }
    },
    BudgetSearchRow: {
      base: 'platformCore:SearchRow',
      elements: {
        basic: {
          type: 'platformCommon:BudgetSearchRowBasic',
          minOccurs: '0'
        }
      }
    }
  };

}).call(this);
